server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 119.3.175.0:8848 #配置Nacos地址
    sentinel:
      transport:
        dashboard: 119.3.175.0:8080
        #port: 8719  #应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
    gateway:
      routes:
        - id: user-service #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9001   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/{path}  #断言,路径相匹配的进行路由
