Server:
  port: 9003

spring:
  application:
    name: comment-service
  cloud:
    nacos:
      discovery:
        server-addr: 119.3.175.0:8848 #配置Nacos地址


dubbo:
  registry:
    address: spring-cloud://119.3.175.0
  protocol:
    name: dubbo
    port: -1